

// Mock data
export const mockMembers = [
  {
    id: '1',
    email: 'john.doe@example.com',
    name: 'John Doe',
    role: 'member',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    phone: '+1234567890',
    membershipType: 'Gold',
    membershipExpiry: '2026-12-31',
    joinDate: '2024-01-15',
    status: 'active',
    createdAt: '2024-01-15',
    accessibleSports: ['Yoga', 'Swimming', 'Gym', 'Tennis'],
    multiClubAccess: true,
    accessibleClubs: ['Downtown Sports Hub', 'Westside Fitness Center'],
    emergencyContact: {
      name: 'Jane Doe',
      phone: '+1234567899',
      relationship: 'Spouse',
    },
    healthInfo: {
      height: 180,
      weight: 75,
      bloodType: 'O+',
      allergies: ['Peanuts'],
      medicalConditions: [],
      medicalCertificateUrl: '#',
      certificateExpiry: '2026-12-31',
    },
  },
  {
    id: '5',
    email: 'alice.smith@example.com',
    name: 'Alice Smith',
    role: 'member',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
    phone: '+1234567894',
    membershipType: 'Platinum',
    membershipExpiry: '2026-06-30',
    joinDate: '2023-12-01',
    status: 'active',
    createdAt: '2023-12-01',
    accessibleSports: ['Yoga', 'Swimming', 'Gym', 'Tennis', 'Pilates', 'Cycling'],
    multiClubAccess: true,
    accessibleClubs: ['Downtown Sports Hub', 'Westside Fitness Center', 'Eastside Club'],
  },
  {
    id: '6',
    email: 'bob.wilson@example.com',
    name: 'Bob Wilson',
    role: 'member',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
    phone: '+1234567895',
    membershipType: 'Silver',
    membershipExpiry: '2026-03-15',
    joinDate: '2024-03-01',
    status: 'pending',
    createdAt: '2024-03-01',
    accessibleSports: ['Gym', 'Swimming'],
    multiClubAccess: false,
    accessibleClubs: ['Downtown Sports Hub'],
  },
];

export const mockCoaches = [
  {
    id: '2',
    email: 'sarah.johnson@example.com',
    name: 'Sarah Johnson',
    role: 'coach',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    phone: '+1234567891',
    specializations: ['Yoga', 'Pilates', 'Meditation'],
    certifications: ['Certified Yoga Instructor', 'Pilates Master'],
    bio: 'Experienced yoga and pilates instructor with 10+ years of teaching.',
    rating: 4.8,
    totalSessions: 245,
    approvalStatus: 'approved',
    createdAt: '2024-01-10',
  },
  {
    id: '7',
    email: 'david.lee@example.com',
    name: 'David Lee',
    role: 'coach',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    phone: '+1234567896',
    specializations: ['Swimming', 'Water Aerobics'],
    certifications: ['Lifeguard Certified', 'Swimming Coach Level 3'],
    bio: 'Professional swimming coach specializing in competitive training.',
    rating: 4.9,
    totalSessions: 312,
    approvalStatus: 'approved',
    createdAt: '2023-11-20',
  },
];

export const mockAdmins = [
  {
    id: '3',
    email: 'admin@test.com',
    name: 'Mike Admin',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    phone: '+1234567892',
    permissions: ['manage_members', 'manage_coaches', 'manage_facilities', 'view_reports'],
    lastLogin: '2026-01-22T10:30:00Z',
    twoFactorEnabled: true,
    createdAt: '2024-01-05',
  },
];

// Mock sessions data (kept for coach/admin functionality)
export const mockSessions = [
  {
    id: 's1',
    title: 'Morning Yoga Flow',
    sport: 'Yoga',
    coachId: '2',
    coachName: 'Sarah Johnson',
    coachAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    date: '2026-01-23',
    startTime: '07:00',
    endTime: '08:00',
    location: 'Studio A',
    capacity: 20,
    bookedCount: 15,
    price: 25,
    description: 'Start your day with energizing yoga flow suitable for all levels.',
    difficulty: 'Beginner',
    status: 'scheduled',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/36f0a43c-5afe-42bf-8fef-68eef36ee9ec.png',
  },
  {
    id: 's2',
    title: 'Advanced Swimming Techniques',
    sport: 'Swimming',
    coachId: '7',
    coachName: 'David Lee',
    coachAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    date: '2026-01-23',
    startTime: '09:00',
    endTime: '10:30',
    location: 'Pool 1',
    capacity: 12,
    bookedCount: 10,
    price: 40,
    description: 'Improve your swimming technique with professional coaching.',
    difficulty: 'Advanced',
    status: 'scheduled',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/95b292c3-03c8-46e0-b6fe-abaa4426ce3e.png',
  },
  {
    id: 's3',
    title: 'Pilates Core Strength',
    sport: 'Pilates',
    coachId: '2',
    coachName: 'Sarah Johnson',
    coachAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    date: '2026-01-24',
    startTime: '18:00',
    endTime: '19:00',
    location: 'Studio B',
    capacity: 15,
    bookedCount: 12,
    price: 30,
    description: 'Build core strength and improve flexibility with pilates.',
    difficulty: 'Intermediate',
    status: 'scheduled',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/cdd269bf-deb1-450d-ae90-b197f7184d6e.png',
  },
  {
    id: 's4',
    title: 'Evening Meditation',
    sport: 'Meditation',
    coachId: '2',
    coachName: 'Sarah Johnson',
    coachAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    date: '2026-01-25',
    startTime: '19:30',
    endTime: '20:30',
    location: 'Studio A',
    capacity: 25,
    bookedCount: 18,
    price: 20,
    description: 'Relax and unwind with guided meditation session.',
    difficulty: 'Beginner',
    status: 'scheduled',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/cf7c9bab-6268-4340-8b47-f2195b32b430.png',
  },
];

// Biometric Attendance Records (for member portal - walk-in model)
export const mockAttendanceRecords = [
  {
    id: 'att1',
    memberId: '1',
    memberName: 'John Doe',
    clubName: 'Downtown Sports Hub',
    punchInTime: '2026-01-29T07:15:00Z',
    punchOutTime: '2026-01-29T09:30:00Z',
    duration: 135, // minutes
    facility: 'Gym Floor',
    biometricVerified: true,
    date: '2026-01-29',
  },
  {
    id: 'att2',
    memberId: '1',
    memberName: 'John Doe',
    clubName: 'Downtown Sports Hub',
    punchInTime: '2026-01-28T18:00:00Z',
    punchOutTime: '2026-01-28T19:45:00Z',
    duration: 105,
    facility: 'Pool 1',
    biometricVerified: true,
    date: '2026-01-28',
  },
  {
    id: 'att3',
    memberId: '1',
    memberName: 'John Doe',
    clubName: 'Westside Fitness Center',
    punchInTime: '2026-01-27T06:30:00Z',
    punchOutTime: '2026-01-27T08:00:00Z',
    duration: 90,
    facility: 'Studio A',
    biometricVerified: true,
    date: '2026-01-27',
  },
  {
    id: 'att4',
    memberId: '1',
    memberName: 'John Doe',
    clubName: 'Downtown Sports Hub',
    punchInTime: '2026-01-26T17:00:00Z',
    punchOutTime: '2026-01-26T18:30:00Z',
    duration: 90,
    facility: 'Gym Floor',
    biometricVerified: true,
    date: '2026-01-26',
  },
  {
    id: 'att5',
    memberId: '1',
    memberName: 'John Doe',
    clubName: 'Downtown Sports Hub',
    punchInTime: '2026-01-25T07:00:00Z',
    punchOutTime: '2026-01-25T08:15:00Z',
    duration: 75,
    facility: 'Studio A',
    biometricVerified: true,
    date: '2026-01-25',
  },
];

// Current active session (if member is currently punched in)
export const mockActiveSession = null; // Set to null if not punched in

export const mockPayments = [
  {
    id: 'p1',
    memberId: '1',
    amount: 199,
    type: 'membership',
    status: 'paid',
    date: '2026-01-01',
    method: 'card',
    description: 'Gold Membership - January 2026',
    invoiceUrl: '#',
  },
  {
    id: 'p2',
    memberId: '1',
    amount: 199,
    type: 'membership',
    status: 'pending',
    date: '2026-01-22',
    dueDate: '2026-02-01',
    method: 'card',
    description: 'Gold Membership - February 2026',
  },
];

export const mockMessages = [
  {
    id: 'm1',
    senderId: '2',
    senderName: 'Sarah Johnson',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    receiverId: '1',
    subject: 'Yoga Tips for Beginners',
    content: 'Hi John! I noticed you\'ve been using the yoga studio. Here are some tips to improve your practice...',
    timestamp: '2026-01-22T14:30:00Z',
    read: false,
    type: 'inbox',
  },
  {
    id: 'm2',
    senderId: '3',
    senderName: 'Mike Admin',
    senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    receiverId: '1',
    subject: 'Membership Renewal Reminder',
    content: 'Your Gold membership will expire on December 31, 2026. Renew now to continue enjoying all benefits!',
    timestamp: '2026-01-21T09:00:00Z',
    read: true,
    type: 'inbox',
  },
];

export const mockNotifications = [
  {
    id: 'n1',
    userId: '1',
    title: 'Successful Punch-out',
    message: 'You completed a 135-minute session at Gym Floor',
    type: 'success',
    timestamp: '2026-01-29T09:30:00Z',
    read: false,
    actionUrl: '/member/attendance',
  },
  {
    id: 'n2',
    userId: '1',
    title: 'Payment Due',
    message: 'Your membership payment of $199 is due on Feb 1, 2026',
    type: 'warning',
    timestamp: '2026-01-22T10:00:00Z',
    read: false,
    actionUrl: '/member/payments',
  },
  {
    id: 'n3',
    userId: '1',
    title: 'New Message',
    message: 'You have a new message from Sarah Johnson',
    type: 'info',
    timestamp: '2026-01-22T14:30:00Z',
    read: true,
    actionUrl: '/member/messages',
  },
  {
    id: 'n4',
    userId: '1',
    title: 'Facility Maintenance',
    message: 'Pool 1 will be closed for maintenance from Jan 30-31',
    type: 'warning',
    timestamp: '2026-01-28T08:00:00Z',
    read: true,
    actionUrl: '/member/announcements',
  },
];

export const mockFacilities = [
  {
    id: 'f1',
    name: 'Studio A',
    type: 'Yoga Studio',
    capacity: 25,
    location: 'Building 1, Floor 2',
    amenities: ['Mirrors', 'Sound System', 'Air Conditioning', 'Yoga Mats', 'Blocks & Straps'],
    status: 'available',
    sports: ['Yoga', 'Pilates', 'Meditation'],
    safetyRules: [
      'Bring your own mat or use provided mats',
      'No shoes allowed inside',
      'Maintain silence during meditation sessions',
      'Clean equipment after use',
    ],
    maxOccupancy: 25,
    ageRestriction: '16+',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/36f0a43c-5afe-42bf-8fef-68eef36ee9ec.png',
  },
  {
    id: 'f2',
    name: 'Pool 1',
    type: 'Swimming Pool',
    capacity: 20,
    location: 'Building 2, Ground Floor',
    amenities: ['Olympic Size (50m)', 'Heated Water', 'Changing Rooms', 'Showers', 'Lockers'],
    status: 'available',
    sports: ['Swimming', 'Water Aerobics'],
    safetyRules: [
      'Shower before entering pool',
      'No diving in shallow end',
      'Children under 12 must be supervised',
      'Swim caps required',
      'No running on pool deck',
    ],
    maxOccupancy: 20,
    ageRestriction: 'All ages (under 12 with guardian)',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/95b292c3-03c8-46e0-b6fe-abaa4426ce3e.png',
  },
  {
    id: 'f3',
    name: 'Gym Floor',
    type: 'Fitness Center',
    capacity: 50,
    location: 'Building 1, Floor 1',
    amenities: ['Cardio Equipment', 'Free Weights', 'Cable Machines', 'Benches', 'Squat Racks', 'Water Fountains'],
    status: 'available',
    sports: ['Gym', 'Strength Training', 'Cardio'],
    safetyRules: [
      'Wipe down equipment after use',
      'Use collars on barbells',
      'Ask for spotter when lifting heavy',
      'Wear proper athletic shoes',
      'Return weights to racks',
    ],
    maxOccupancy: 50,
    ageRestriction: '16+',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/cdd269bf-deb1-450d-ae90-b197f7184d6e.png',
  },
  {
    id: 'f4',
    name: 'Tennis Court 1',
    type: 'Outdoor Court',
    capacity: 4,
    location: 'Outdoor Area',
    amenities: ['Professional Surface', 'Night Lighting', 'Seating Area', 'Ball Machine Available'],
    status: 'available',
    sports: ['Tennis'],
    safetyRules: [
      'Wear tennis shoes only',
      'No food or drinks on court',
      'Maximum 4 players (doubles)',
      'Book court in advance',
    ],
    maxOccupancy: 4,
    ageRestriction: 'All ages',
    imageUrl: 'https://mgx-backend-cdn.metadl.com/generate/images/924660/2026-01-22/cf7c9bab-6268-4340-8b47-f2195b32b430.png',
  },
];

export const mockAnnouncements = [
  {
    id: 'a1',
    title: 'New Biometric System Installed',
    content: 'We have upgraded our attendance system with biometric fingerprint scanners at all entry points. Simply scan your finger to punch in and out!',
    author: 'Mike Admin',
    targetAudience: ['member', 'coach'],
    priority: 'high',
    publishDate: '2026-01-20',
    expiryDate: '2026-02-20',
    status: 'published',
  },
  {
    id: 'a2',
    title: 'Facility Maintenance - Pool Closed',
    content: 'Pool 1 will be closed for maintenance from Jan 30-31. We apologize for the inconvenience. Pool 2 will remain open.',
    author: 'Mike Admin',
    targetAudience: ['member', 'coach', 'admin'],
    priority: 'high',
    publishDate: '2026-01-22',
    expiryDate: '2026-01-31',
    status: 'published',
  },
  {
    id: 'a3',
    title: 'Extended Hours This Weekend',
    content: 'Great news! All facilities will be open from 6 AM to 11 PM this weekend. Enjoy extended access!',
    author: 'Mike Admin',
    targetAudience: ['member'],
    priority: 'medium',
    publishDate: '2026-01-28',
    expiryDate: '2026-02-02',
    status: 'published',
  },
];

export const mockComplaints = [
  {
    id: 'c1',
    memberId: '5',
    memberName: 'Alice Smith',
    subject: 'Locker Room Cleanliness',
    description: 'The women\'s locker room needs better maintenance. Noticed several issues with cleanliness.',
    category: 'Facilities',
    priority: 'medium',
    status: 'in-progress',
    assignedTo: 'Mike Admin',
    createdAt: '2026-01-20T10:00:00Z',
  },
  {
    id: 'c2',
    memberId: '6',
    memberName: 'Bob Wilson',
    subject: 'Biometric Scanner Not Working',
    description: 'The fingerprint scanner at the main entrance was not working this morning. Had to use manual sign-in.',
    category: 'Technical',
    priority: 'high',
    status: 'open',
    createdAt: '2026-01-22T08:30:00Z',
  },
];

export const mockBranches = [
  {
    id: 'br1',
    name: 'Downtown Sports Hub',
    address: '123 Main Street',
    city: 'New York',
    country: 'USA',
    phone: '+1234567800',
    email: 'downtown@sportshub.com',
    manager: 'Mike Admin',
    totalMembers: 450,
    totalRevenue: 125000,
    status: 'active',
    facilities: ['Studio A', 'Pool 1', 'Gym Floor', 'Tennis Court 1'],
  },
  {
    id: 'br2',
    name: 'Westside Fitness Center',
    address: '456 West Avenue',
    city: 'Los Angeles',
    country: 'USA',
    phone: '+1234567801',
    email: 'westside@sportshub.com',
    manager: 'Jane Manager',
    totalMembers: 380,
    totalRevenue: 98000,
    status: 'active',
    facilities: ['Studio A', 'Pool 2', 'Gym Floor'],
  },
  {
    id: 'br3',
    name: 'Eastside Club',
    address: '789 East Boulevard',
    city: 'Chicago',
    country: 'USA',
    phone: '+1234567802',
    email: 'eastside@sportshub.com',
    manager: 'Tom Director',
    totalMembers: 320,
    totalRevenue: 85000,
    status: 'active',
    facilities: ['Studio B', 'Pool 1', 'Gym Floor', 'Basketball Court'],
  },
];

export const mockMembershipPlans = [
  {
    id: 'plan1',
    name: 'Basic',
    price: 49,
    duration: 1,
    features: ['Access to gym', 'Locker room access', 'Single club access'],
    sports: ['Gym'],
    multiClubAccess: false,
    trialDays: 7,
    color: 'gray',
  },
  {
    id: 'plan2',
    name: 'Silver',
    price: 99,
    duration: 1,
    features: ['All Basic features', 'Pool access', 'Yoga & Pilates classes', 'Single club access'],
    sports: ['Gym', 'Swimming', 'Yoga', 'Pilates'],
    multiClubAccess: false,
    trialDays: 14,
    color: 'slate',
  },
  {
    id: 'plan3',
    name: 'Gold',
    price: 199,
    duration: 1,
    features: ['All Silver features', 'Tennis court access', 'Multi-club access (2 clubs)', 'Priority support'],
    sports: ['Gym', 'Swimming', 'Yoga', 'Pilates', 'Tennis'],
    multiClubAccess: true,
    accessibleClubsCount: 2,
    trialDays: 14,
    popular: true,
    color: 'yellow',
  },
  {
    id: 'plan4',
    name: 'Platinum',
    price: 299,
    duration: 1,
    features: ['All Gold features', 'All sports access', 'Multi-club access (all clubs)', 'Guest passes', 'Exclusive events'],
    sports: ['Gym', 'Swimming', 'Yoga', 'Pilates', 'Tennis', 'Cycling', 'Basketball'],
    multiClubAccess: true,
    accessibleClubsCount: 'unlimited',
    trialDays: 30,
    color: 'purple',
  },
];

export const sports = ['Yoga', 'Pilates', 'Swimming', 'Tennis', 'Basketball', 'Meditation', 'Cycling', 'Boxing', 'Dance', 'Martial Arts'];
export const locations = ['Studio A', 'Studio B', 'Pool 1', 'Pool 2', 'Gym Floor', 'Court 1', 'Court 2', 'Outdoor Area'];
